package com.tbyf.entity.hm.cismain;

import java.util.Date;

public class CisMain {
		
	private String bah;  //病案号
	private String bazl;  //病案质量
	private Integer bdbzpf;  //白蛋白类制品费
	private String blh;  //病理号
	private Integer blzdf;  //病理诊断费
	private String bmygh;  //编码员工号
	private String bmyxm;  //编码员姓名
	private String bz;  //备注
	private Integer cgcs;  //成功次数
	private String ch;  //床号
	private Integer chcyl;  //产后出血量
	private Integer clf;  //材料费
	private String crbbg;  //有传染病报告
	private String csd;  //出生地
	private String csny;  //出生日期
	private String cybq;  //出院病区（房）
	private String cyksbm;  //出院科室编码
	private Date cysj;  //出院时间
	private String dqbm;  //地区
	private String fsblzd;  //放射病理诊断符合编码
	private Integer fsszlxmf;  //非手术治疗项目费
	private String fzrysgh;  //副主任医师工号
	private String fzrysxm;  //副主任医师姓名
	private String gj;  //国籍
	private String gzdw;  //工作单位
	private String gzdwdh;  //工作单位电话
	private String gzdwyb;  //工作单位邮编
	private String hbsag_jg;  //HBSAG检查结果编码
	private String hcvab_jg;  //HCVab检查结果编码
	private String hivab_jg;  //HIVab检查结果编码
	private String hkdh;  //户口电话
	private String hkdz;  //户口地址
	private String hkyb;  //户口邮编
	private Integer hlf;  //护理费
	private String hszgh;  //护士长工号
	private String hszxm;  //护士长姓名
	private Integer hxbsxl;  //红细胞输血量
	private Integer hyf;  //化验费
	private String hyzk;  //婚姻状况
	private String isbzsh;  //辨证施护
	private String isjgzyzj;  //使用医疗机构中药制剂
	private String iszyzljs;  //使用中医诊疗技术
	private String iszyzlsb;  //使用中医诊疗设备
	private Integer jcf;  //检查费
	private Integer jcyyclf;  //检查用一次性医用材料费
	private String jdbm;  //街道
	private String jg;  //籍贯
	private String jkkh;  //健康卡号
	private String jxysgh;  //进修医师工号
	private String jxysxm;  //进修医师姓名
	private String jzd;  //居住地（现住址）
	private String jzlsh;  //住院就诊流水号
	private Integer kff;  //康复费
	private String kh;  //卡号
	private Integer kjywfy;  //抗菌药物费用
	private String klx;  //卡类型
	private String kzrgh;  //科主任工号
	private String kzrxm;  //科主任姓名
	private String lcblzd;  //临床病理诊断符合编码
	private Integer lcwlzlf;  //临床物理治疗费
	private Integer lczdxmf;  //临床诊断项目费
	private String lxdh;  //联系电话
	private String lxrdh;  //联系人电话
	private String lxrdz;  //联系人地址
	private String lxrgx;  //联系人与患者的关系
	private String lxrtxdz;  //联系人通信地址
	private String lxrxm;  //联系人姓名
	private String lyfs;  //离院方式
	private String mj;  //密级
	private String mz;  //民族
	private String mzcyzd;  //门诊出院诊断符合编码
	private Integer mzf;  //麻醉费
	private String mzysgh;  //门诊医师工号
	private String mzysxm;  //门诊医师姓名
	private String njsyymc;  //离院后拟接收医疗机构名称
	private Integer nxyzzpf;  //凝血因子类制品费
	private String personid;  //院内患者唯一ID号
	private Integer qdbzpf;  //球蛋白类制品费
	private Integer qjcs;  //抢救次数
	private String qtbg;  //有其它报告
	private Integer qtf;  //其他费用
	private Integer qtf_1;  //其他费
	private Integer qtsxl;  //其它输血量
	private String qxbm;  //区县
	private Integer qxsxl;  //全血输血量
	private String qzrq;  //确诊日期
	private String rsmdsc;  //是否妊娠梅毒筛查
	private String rybq;  //入院病区（房）
	private String rycyzd;  //入院出院诊断符合编码
	private String ryhhmsj;  //颅脑损伤患者入院后昏迷时间
	private String ryksbm;  //入院科室编码
	private String rylx;  //入院途径(1：门诊入院、2：急诊入院、3：其他医疗机构转入、9：其他)
	private String ryqhmsj;  //颅脑损伤患者入院前昏迷时间
	private String ryqk;  //入院病情
	private String ryqwyzz;  //入院前经外院诊治
	private Date rysj;  //入院时间
	private String sfcxwjn;  //住院是否出现危重、急症、疑难
	private String sfkyba;  //是否为科研病案
	private String sfz;  //身份证号
	private String sj;  //（死亡患者）是否尸检
	private String sjbl;  //是否示教病例
	private Integer sjzyts;  //实际住院天数
	private String sqshzd;  //术前术后诊断符合编码
	private String ssdyl;  //手术治疗检查诊断为本院第一例
	private Integer ssf;  //手术费
	private String sslclj;  //实施临床路径
	private Integer ssyyclf;  //手术用一次性医用材料费
	private String sszd;  //损伤中毒的外部因素
	private String sszdbm;  //损伤中毒的外部原因的疾病编码
	private Integer sszlf;  //手术治疗费
	private String swbg;  //孕产妇死亡报告
	private String swgbyy;  //死亡根本原因
	private Date swsj;  //死亡时间
	private String sxfy;  //有输血反应
	private String sxysgh;  //实习医师工号
	private String sxysxm;  //实习医师姓名
	private String syfy;  //输液反应
	private Integer syszdf;  //实验室诊断费
	private String sz;  //是否随诊
	private String szbq;  //所转病区
	private Integer szqx;  //随诊期限
	private String szqxdw;  //随诊期限单位
	private String xb;  //性别
	private Integer xbyzzpf;  //细胞因子类制品费
	private Integer xf;  //血费
	private Integer xgbz;  //修改标志(0：正常、1：撤销；)
	private Integer xjsxl;  //血浆输血量
	private String xm;  //姓名
	private String xsebg;  //有新生儿死亡报告
	private Integer xsecstz;  //新生儿出生体重
	private String xsejbsc;  //新生儿疾病筛查
	private Integer xserytz;  //新生儿入院体重
	private Integer xse_tz;  //新生儿体重
	private String xse_xb;  //新生儿性别
	private String xx;  //血型
	private Integer xxbsxl;  //血小板输血量
	private Integer xyf;  //西药费
	private String xzzdh;  //现住址电话
	private String xzzyb;  //现住址邮编
	private Integer ylfwf;  //一般医疗服务费
	private String ylfylylb;  //医疗费用来源类别
	private String yljgdm;  //医疗机构代码
	private String ylyl1;  //预留一
	private String ylyl2;  //预留二
	private String ywgm;  //药物过敏
	private Integer yxxzdf;  //影像学诊断费
	private String yygrjg;  //医院感染结果
	private String yygrmc;  //医院感染名称
	private Integer zcaf;  //中草药费
	private Integer zcyf;  //中成药费
	private Integer zcyjff;  //针刺与灸法费
	private Integer zfje;  //自付金额
	private Integer zfy;  //总费用
	private Integer zhf;  //治疗费
	private String zkhsgh;  //质控护士工号
	private String zkhszm;  //质控护士姓名
	private String zkksbm1;  //转科科室编码1
	private String zkksbm2;  //转科科室编码2
	private String zkksbm3;  //转科科室编码3
	private Date zkrq;  //质控日期
	private String zkysgh;  //质控医师工号
	private String zkysxm;  //质控医师姓名
	private String zlbg;  //有肿瘤报告
	private Integer zlczf;  //一般治疗操作费
	private Integer zlf;  //诊疗费
	private String zllb;  //治疗类别
	private Integer zlyyclf;  //治疗用一次性医用材料费
	private String zrhsgh;  //责任护士工号
	private String zrhsxm;  //责任护士姓名
	private String zrysgh;  //主任医师工号
	private String zrysxm;  //主任医师姓名
	private String zybm;  //职业
	private Integer zybzlzf;  //中医辨证论治费
	private Integer zybzlzhzf;  //中医辨证论治会诊费
	private Integer zycs;  //住院次数
	private Integer zyf;  //住院费
	private Integer zygczlf;  //中医肛肠治疗费
	private Integer zygsf;  //中医骨伤费
	private Integer zyqtf;  //中医其他费
	private Integer zytnzlf;  //中医推拿治疗费
	private Integer zytstpf;  //中药特殊调配加工费
	private Integer zytszlf;  //中医特殊治疗费
	private Integer zywzf;  //中医外治费
	private String zyysgh;  //住院医师工号
	private String zyysxm;  //住院医师姓名
	private Integer zyzdf;  //中医诊断费
	private Integer zyzjf;  //医疗机构中药制剂费
	private Integer zyzlf;  //中医治疗费
	private String zzyjh_31;  //是否有出院31天内再住院计划
	private String zzysgh;  //主治医师工号
	private String zzysxm;  //主治医师姓名
}
