
package com.tbyf.ehrclient.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-10T10:58:15.509+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class UserGeneralRemote_UserGenerLogicPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.ehr.tbyf.com/", "UserGenerLogicService");

    private UserGeneralRemote_UserGenerLogicPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserGenerLogicService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserGenerLogicService ss = new UserGenerLogicService(wsdlURL, SERVICE_NAME);
        UserGeneralRemote port = ss.getUserGenerLogicPort();  
        
        {
        System.out.println("Invoking checkPatientArchives...");
        java.lang.String _checkPatientArchives_arg0 = "";
        java.lang.String _checkPatientArchives__return = port.checkPatientArchives(_checkPatientArchives_arg0);
        System.out.println("checkPatientArchives.result=" + _checkPatientArchives__return);


        }
        {
        System.out.println("Invoking checkSpecialFile...");
        java.lang.String _checkSpecialFile_arg0 = "";
        java.lang.String _checkSpecialFile__return = port.checkSpecialFile(_checkSpecialFile_arg0);
        System.out.println("checkSpecialFile.result=" + _checkSpecialFile__return);


        }
        {
        System.out.println("Invoking addSfjlHypertension...");
        java.lang.String _addSfjlHypertension_arg0 = "";
        java.lang.String _addSfjlHypertension__return = port.addSfjlHypertension(_addSfjlHypertension_arg0);
        System.out.println("addSfjlHypertension.result=" + _addSfjlHypertension__return);


        }
        {
        System.out.println("Invoking patientArchives...");
        java.lang.String _patientArchives_arg0 = "";
        java.lang.String _patientArchives__return = port.patientArchives(_patientArchives_arg0);
        System.out.println("patientArchives.result=" + _patientArchives__return);


        }
        {
        System.out.println("Invoking addSfjlMentalillness...");
        java.lang.String _addSfjlMentalillness_arg0 = "";
        java.lang.String _addSfjlMentalillness__return = port.addSfjlMentalillness(_addSfjlMentalillness_arg0);
        System.out.println("addSfjlMentalillness.result=" + _addSfjlMentalillness__return);


        }
        {
        System.out.println("Invoking getPatientInfo...");
        java.lang.String _getPatientInfo_arg0 = "";
        java.lang.String _getPatientInfo__return = port.getPatientInfo(_getPatientInfo_arg0);
        System.out.println("getPatientInfo.result=" + _getPatientInfo__return);


        }
        {
        System.out.println("Invoking buildSpecialFile...");
        java.lang.String _buildSpecialFile_arg0 = "";
        java.lang.String _buildSpecialFile__return = port.buildSpecialFile(_buildSpecialFile_arg0);
        System.out.println("buildSpecialFile.result=" + _buildSpecialFile__return);


        }
        {
        System.out.println("Invoking addSfjlDiabetes...");
        java.lang.String _addSfjlDiabetes_arg0 = "";
        java.lang.String _addSfjlDiabetes__return = port.addSfjlDiabetes(_addSfjlDiabetes_arg0);
        System.out.println("addSfjlDiabetes.result=" + _addSfjlDiabetes__return);


        }

        System.exit(0);
    }

}
